"""Dates a coder has filled in for documents Zotero has none for.

`doc_dates.json` maps {doc_key: "YYYY-MM-DD"}. It is shared across coders (when an
article was published is a fact about the article, not anyone's judgement) and it
sits beside zotero_docs.csv rather than in it, because the CSV is regenerated by
every Zotero import and would lose them. A date Zotero does supply always wins;
this only fills the gaps. It is mirrored to Atlas on each document's own
`documents[].date`, so a host whose disk is rebuilt gets them back.

Imports nothing from the rest of the app, so mongo_sync and storage can both use it.
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).parent
DATES_JSON = HERE / "doc_dates.json"
_ISO = re.compile(r"\d{4}-\d{2}-\d{2}")
_cache = {"mtime": None, "data": {}}


def load() -> dict:
    """The local file, re-read only when it changes."""
    mtime = DATES_JSON.stat().st_mtime if DATES_JSON.exists() else None
    if mtime != _cache["mtime"]:
        try:
            _cache["data"] = json.loads(DATES_JSON.read_text() or "{}") if mtime else {}
        except ValueError:
            _cache["data"] = {}
        _cache["mtime"] = mtime
    return _cache["data"]


def valid(date: str) -> bool:
    """A real calendar date, written YYYY-MM-DD (or blank, which clears it)."""
    if not date:
        return True
    if not _ISO.fullmatch(date):
        return False
    from datetime import date as _d
    try:
        _d.fromisoformat(date)
    except ValueError:
        return False
    return True


def effective(key: str, csv_date: str = "") -> str:
    """Zotero's date if it has one, else the one filled in here."""
    return csv_date or load().get(key, "")


def save(key: str, date: str) -> None:
    data = dict(load())
    if date:
        data[key] = date
    else:
        data.pop(key, None)
    tmp = DATES_JSON.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(dict(sorted(data.items())), indent=2) + "\n")
    tmp.replace(DATES_JSON)
